apiVersion: v1
kind: Service
metadata:
  name: imageezgen3d
  labels:
    app.kubernetes.io/name: imageezgen3d
spec:
  selector:
    app.kubernetes.io/name: imageezgen3d
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7865
  type: ClusterIP